name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Wow! You just created your issue in this repo! Thank you so much!'' First Issue'
        pr-message: 'Oh my gosh oh my gosh oh my gosh! You really made a new PR? Thank you thank you thank you!'' First PR'
